Removes the chunky fingers trait from Insulated gloves.
Artea-Station/Artea-Station-Server pull request #157
Opened 2023-04-16 19:47 UTC by QuacksQ

## About The Pull Request
Removes the Chunky fingers trait from Insulated gloves.

Why? Because I hate having to take my gloves off when I'm playing engineering to interact with consoles or to preform other tasks. (Yes this is a salt PR)

## How Does This Help ***Gameplay***?
Engineers can now interact with consoles properly again while they are wearing insuls along with doing other things previously barred because of the chunky fingers trait on these gloves.

## How Does This Help ***Roleplay***?
Minimal impact on Roleplay.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary> 

https://user-images.githubusercontent.com/79924768/232338085-2591067d-4e06-472d-83cd-f95509b5d13f.mp4

</details>

## Changelog
:cl:
del: Removes the chunky fingers trait from Insuls. 
/:cl:

2023-04-20 15:48 UTC, RimiNosha requested changes
Then my recommendation is to remove the chunky fingers block from tablets and computers, unless you want to add a new trait that flags chunky finger gloves that it's given to as usable on them.

2023-04-21 15:55 UTC, QuacksQ commented
> Golems and hulks are not staying, that is correct.
> 
> The laser pointer check makes sense, as (especially when upgraded) it can very easily cripple anyone who doesn't have sunglasses (borgs included) if you're an accurate clicker, or they're standing still.
> 
> My recommendation is to remove the chunky fingers block from tablets and computers, unless you want to add a new trait that flags chunky finger gloves that it's given to as usable on them.

Removed the chunky fingers block from computers, Tablets never had them in the first place (and we dont have tablets as of #115)

2023-04-21 21:46 UTC, RimiNosha requested changes

2023-04-21 21:46 UTC, RimiNosha commented on code/modules/clothing/gloves/color.dm
> +	desc = "These gloves provide protection against electric shock."
Don't forget to undo the chunky fingers stuff for the gloves and update your PR title and body.

2023-04-21 21:46 UTC, RimiNosha commented on code/modules/clothing/gloves/color.dm
> -	clothing_traits = list(TRAIT_CHUNKYFINGERS)
Ditto.

2023-04-22 00:44 UTC, QuacksQ commented
Requested changes made, PR title and description/comment have been updated. pls re-review for the millionth time 🙏

2023-04-22 06:19 UTC, nevimer commented
I am of the opinion that the whole chunky fingers concept is ridiculous anyways. People wear gloves when working with tools and computers, especially in real life, and in game it makes no sense. Trait should be reserved for like, species only, and even then... it doesn't need to exist in our setting?

2023-04-26 18:37 UTC, RimiNosha commented
For now, the computers issue is the one that was front and center in this PR, if we wanna have a deep look into how chunky fingers affects things (keeping in mind all races with chunky fingers are gone), then we can make another.

2023-04-26 18:37 UTC, RimiNosha approved these changes
Yeet.

2023-04-26 18:57 UTC, merged