[Paperwork] adds Internal affairs agents from paradise.
Artea-Station/Artea-Station-Server pull request #54
Opened 2023-02-26 19:07 UTC by QuacksQ

## About The Pull Request
Adds Internal Affairs agents as a new command job with 2 slots to the game.
Internal affairs agents are tasked with making sure SOP (Standard Operating Procedure) is followed on station.

## How Does This Help ***Gameplay***?
New job for people to play around with and this is also the perfect job for paperwork mains.

## How Does This Help ***Roleplay***?
IAA is tasked with making sure people follow SOP, failure to do so will result in a report or demotion etc etc, they generate roleplay basically and are a form of enforcing IC rules.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary> 

![](https://i.gyazo.com/b3b64c18390e539a0963861dd8d93dc9.png)

![](https://i.gyazo.com/fbfba56629dcda54224a7fa3d533fb4d.png)

![](https://i.gyazo.com/3ba92e33a6880e4d99327cd5a4f1cd91.png)

</details>

## Changelog

:cl:
add: Adds Internal affairs agents to the game.
/:cl:

2023-02-26 20:15 UTC, nevimer requested changes
just some better placement

2023-02-26 20:15 UTC, nevimer commented on code/game/objects/effects/landmarks.dm
> +/obj/effect/landmark/start/internal_affairs_agent
move this to a better spot, not between ai and cyborg

2023-02-26 20:15 UTC, nevimer commented on code/game/objects/items/devices/radio/encryptionkey.dm
> +/obj/item/encryptionkey/headset_internalaffairs
ditto

2023-02-26 20:15 UTC, nevimer commented on code/game/objects/items/devices/radio/headset.dm
> +/obj/item/radio/headset/headset_internalaffairs
newline at the end for organizing better please, spacing entries

2023-02-26 20:15 UTC, nevimer commented on code/modules/modular_computers/computers/item/role_tablet_presets.dm
> + * Internal Affairs Agent
move this after the warden and before engineering

2023-02-26 20:49 UTC, nevimer approved these changes
looks alright! There might be missed bits that sneak in, but we can sort those out when noticed.

2023-02-27 03:02 UTC, nevimer requested changes
Silver ID for them, as you are making them a part of command :P

2023-02-28 01:11 UTC, QuacksQ commented
> Silver ID for them, as you are making them a part of command :P

![image](https://user-images.githubusercontent.com/79924768/221726474-dd2306eb-cdfb-490e-88d6-a353e389b901.png)
Silver ID on there now.

2023-02-28 01:24 UTC, nevimer approved these changes
merging in an hour.

2023-02-28 02:06 UTC, merged