TGUI Latejoin Menu! (#71531)
Artea-Station/Artea-Station-Server pull request #65
Opened 2023-03-06 01:42 UTC by nevimer

## About The Pull Request

Converts the latejoin menu to TGUI, and makes it give reasons for why a job is unavailable instead of hiding it!

<details>
<summary>Cool Images!</summary>

<image
src=https://user-images.githubusercontent.com/106692773/205135570-c8b788f1-1ff0-4e6d-b53d-e2119317c37b.png> <image
src=https://user-images.githubusercontent.com/106692773/205135598-2ac9e138-37dc-4baf-ae33-deb0990616cd.png> <image
src=https://user-images.githubusercontent.com/106692773/205135609-ae6b840b-40b5-4248-bd30-5fdadd6582f2.png> <image
src=https://user-images.githubusercontent.com/106692773/205135615-d8997834-f433-48ee-8763-274e306b521b.png>

</details>

## Why It's Good For The Game

TGUI menu good, yes?
## Changelog
:cl: RimiNosha
qol: The latejoin menu is now TGUI!
qol: You'll also be able to see why you can't join a job, instead of it being invisible!
code: Department UI colors have changed slightly. This will only affect the latejoin and nations UIs.
/:cl:

Co-authored-by: Mothblocks <35135081+Mothblocks@users.noreply.github.com>
Co-authored-by: Aleksej Komarov <stylemistake@gmail.com>
# Conflicts:
#	tgui/packages/tgui/interfaces/Orbit.tsx
#	tgui/packages/tgui/interfaces/Orbit/constants.ts

## About The Pull Request

## How Does This Help ***Gameplay***?

## How Does This Help ***Roleplay***?

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary> 

</details>

## Changelog

:cl:
add: TGUI Latejoin Menu by Rimi
/:cl:

2023-03-06 16:23 UTC, RimiNosha requested changes

2023-03-06 16:23 UTC, RimiNosha commented on code/modules/mob/dead/new_player/new_player.dm
> -/mob/dead/new_player/Topic(href, href_list[])
So, TG realised after it was merged, but removing this proc wholesale breaks polls. Please restore lines 41-49, and lines 108-114.

2023-03-06 16:23 UTC, RimiNosha commented on tgui/packages/tgui/interfaces/common/JobToIcon.ts
> +export const JobToIcon = {
Remove this file entirely, and please just port orbit icons, even if they're used for just this menu.

I had a quick glance at the menu without the icons, and it doesn't look nice to me.

See yogstation's port of this to see what you'd need to do. It's surprisingly little.

2023-03-06 16:29 UTC, RimiNosha commented
PRs to also put on top of this before I can accept this:

https://github.com/tgstation/tgstation/pull/72263
https://github.com/tgstation/tgstation/pull/71868
https://github.com/tgstation/tgstation/pull/71883
https://github.com/tgstation/tgstation/pull/71959

2023-03-16 17:41 UTC, RimiNosha commented on tgui/packages/tgui/interfaces/common/JobToIcon.ts
> +export const JobToIcon = {
I hate this file, but this can be removed for DM-sided everything later.

2023-03-16 17:49 UTC, RimiNosha commented
Still missing https://github.com/tgstation/tgstation/pull/72263

2023-03-27 20:26 UTC, RimiNosha requested changes
Make this change, and it should be good to merge.

2023-03-27 20:26 UTC, RimiNosha commented on tgui/packages/tgui/components/index.js
> +export { StyleableSection } from './StyleableSection';
Remove this line.

2023-03-27 22:08 UTC, RimiNosha requested changes
Do this, and it should pass lints.

2023-03-27 22:46 UTC, RimiNosha approved these changes
Oh hey, it passed.

2023-03-28 05:21 UTC, nevimer commented
https://user-images.githubusercontent.com/77420409/228135823-2fe8a3a1-55e2-4c4b-8a79-29059a37ded4.mp4

2023-03-28 05:21 UTC, merged